# Generated by Django 4.2.9 on 2025-08-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casamobler', '0002_remove_usuario_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre_cliente',
            new_name='p_apellidoc',
        ),
        migrations.AddField(
            model_name='cliente',
            name='p_nombrec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='s_apellidoc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='s_nombrec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
