# Generated by Django 4.2.9 on 2025-09-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casamobler', '0003_rename_nombre_cliente_cliente_p_apellidoc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_usuario',
            new_name='p_apellido',
        ),
        migrations.AddField(
            model_name='usuario',
            name='p_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='s_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='s_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
