# Generated by Django 4.2.9 on 2025-09-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casamobler', '0006_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
