# Generated by Django 4.2.9 on 2025-09-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casamobler', '0007_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
