# Generated by Django 4.2.9 on 2025-09-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casamobler', '0008_alter_cliente_direccion_alter_cliente_documento_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
