# Generated by Django 4.2.9 on 2025-09-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Casamobler', '0010_remove_pedido_estado_pedido_remove_pedido_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibocaja',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Casamobler.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='concepto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Valor_Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Valor_Unitario'),
        ),
        migrations.AlterField(
            model_name='recibocaja',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Forma_Pago'),
        ),
        migrations.AlterField(
            model_name='recibocaja',
            name='valor_abonado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor_Abonado'),
        ),
    ]
