# Generated by Django 4.2.9 on 2025-09-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Casamobler', '0012_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('monto_pago', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_producto', models.CharField(blank=True, max_length=200, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recibocaja',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='recibocaja',
            name='pedido',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='p_apellidoc',
            new_name='primer_apellido_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='p_nombrec',
            new_name='primer_nombre_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='s_apellidoc',
            new_name='segundo_apellido_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='s_nombrec',
            new_name='segundo_nombre_cliente',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='rol',
            new_name='Rol',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='p_apellido',
            new_name='primer_apellido_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='p_nombre',
            new_name='primer_nombre_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='s_apellido',
            new_name='segundo_apellido_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='s_nombre',
            new_name='segundo_nombre_usuario',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='estado_garantia',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='descripcion_producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor_unitario',
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='Documento ID'),
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='ReciboCaja',
        ),
        migrations.AddField(
            model_name='pago',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Casamobler.cliente'),
        ),
        migrations.AddField(
            model_name='pago',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Casamobler.pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Casamobler.producto'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Casamobler.producto'),
        ),
    ]
