# Generated by Django 4.2.9 on 2025-09-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Casamobler', '0013_pago_producto_remove_recibocaja_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='valor_total',
        ),
    ]
