# Generated by Django 4.2.9 on 2025-10-22 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Casamobler', '0014_remove_pedido_valor_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Casamobler.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Casamobler.producto')),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Casamobler.remision')),
            ],
        ),
    ]
