# Generated by Django 4.2.9 on 2025-10-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casamobler', '0015_remision_detalleremision'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
