# Generated by Django 4.2.9 on 2025-10-28 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Casamobler', '0016_perfil_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Casamobler.perfil', verbose_name='Responsable'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
