# Generated by Django 4.2.9 on 2025-10-29 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Casamobler', '0017_perfil_second_last_name_perfil_second_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
