# Generated by Django 4.2.9 on 2025-10-29 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Casamobler', '0018_alter_pedido_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='responsable',
        ),
    ]
