# Generated by Django 4.2.9 on 2025-10-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casamobler', '0019_remove_pedido_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
